/** 展览档案室设计提醒：关于页像作者索引卡，信息真实、简练，并与项目页面共享档案化事实层级。 */
import { ArrowUpRight, Download } from "lucide-react";
import { Link } from "wouter";
import { portfolioPdf } from "@/data/portfolio";
import { useLanguage } from "@/contexts/LanguageContext";

const copy = { fr:{ kicker:"À propos", title:"Min Gao", lead:"Designer franco-chinoise, je travaille à l’intersection du design stratégique, de l’expérience de marque et des cultures matérielles.", body:"Mon approche relie l’analyse d’un contexte, la construction d’un récit et la précision de l’expérience. J’aborde l’espace, l’objet, l’interface et l’édition comme des moyens de rendre visibles de nouvelles relations entre personnes, institutions et territoires.", education:"Formation", degree:"Master 2 Design et Numérique", school:"Université Paris-Saclay", program:"M2 Ingénierie en Stratégie du Design (ISD)", focus:"Champs", focusText:"Stratégie · espace · identité · interaction · objet", based:"Basée entre Paris et Shanghai", projects:"Voir les projets", contact:"Contact", download:"Télécharger le portfolio PDF" }, en:{ kicker:"About", title:"Min Gao", lead:"A Franco-Chinese designer working at the intersection of strategic design, brand experience and material cultures.", body:"My approach connects contextual analysis, narrative construction and the precision of experience. I approach space, object, interface and editorial design as ways to make new relationships among people, institutions and territories visible.", education:"Education", degree:"Master 2 Design & Digital", school:"Université Paris-Saclay", program:"M2 Engineering in Design Strategy (ISD)", focus:"Focus", focusText:"Strategy · space · identity · interaction · object", based:"Based between Paris and Shanghai", projects:"View projects", contact:"Contact", download:"Download portfolio PDF" } };

export default function About() { const { language } = useLanguage(); const t = copy[language]; return <main className="page-main about-page"><section className="about-intro"><p className="kicker"><i />03 / {t.kicker}</p><div className="about-main"><div><h1>{t.title}</h1><p className="about-lead">{t.lead}</p><p className="about-body">{t.body}</p></div><aside className="about-status"><i className="mg-seal" aria-hidden="true" /><span>AUTHOR FILE / 03</span><p>{t.based}</p></aside></div></section><section className="about-index"><div><span>01</span><h2>{t.education}</h2><p>{t.degree}<br />{t.school}<br />{t.program}</p></div><div><span>02</span><h2>{t.focus}</h2><p>{t.focusText}</p></div><div><span>03</span><h2>ARCHIVE</h2><a href={portfolioPdf} target="_blank" rel="noreferrer"><Download size={15} />{t.download}</a></div></section><section className="about-links"><Link href="/projects">{t.projects}<ArrowUpRight size={22} /></Link><Link href="/contact">{t.contact}<ArrowUpRight size={22} /></Link></section></main>; }
