import { ArrowUpRight, ArrowLeft } from "lucide-react";
import { Link } from "wouter";
import { useLanguage } from "@/contexts/LanguageContext";

const asset = (file: string) => `${import.meta.env.BASE_URL}assets/annex/${file}`;
const plates = [1, 2, 3, 4, 5, 6, 7].map((n) => asset(`plate-${n}.jpg`));

const copy = {
  fr: {
    back: "Retour au portfolio", kicker: "ANNEXE / CANDIDATURE", title: "Tutoring peinture", intro: "Regarder avant de représenter.", description: "Un dossier complémentaire consacré à l’observation, à la couleur, au dessin d’espace et au croquis de design industriel.", method: "Annexe", methodText: "Cette sélection accompagne le portfolio principal en rendant visibles les compétences de regard, de précision et de construction qui soutiennent ma pratique du design.", observation: "01 / Observation & couleur", observationTitle: "Reproduction d’objets", observationText: "Deux études au crayon de couleur et une coupe de fruit : surface, lumière, matière et structure sont abordées par la même attention au détail.", space: "02 / Regard spatial", spaceTitle: "Croquis du bâtiment", spaceText: "Un croquis urbain construit par la ligne, la profondeur et le rythme des façades — une étude de l’espace comme expérience située.", product: "03 / Analyse & projet", productTitle: "Analyse du produit", productText: "De l’objet démonté aux scénarios d’usage, cette planche montre le passage de l’observation à l’analyse formelle et fonctionnelle.", industrial: "04 / Croquis de design industriel", industrialTitle: "Formes, systèmes, imaginaires", industrialText: "Une série de recherches colorées autour d’objets, de systèmes et de leurs usages : PET FED, FLYER, RICE COOKER et DIGITAL.", plate: "Planche", close: "Fin de l’annexe", next: "Retour aux projets"
  },
  en: {
    back: "Back to portfolio", kicker: "ANNEX / APPLICATION", title: "Painting tutoring", intro: "Look before representing.", description: "A complementary dossier devoted to observation, colour, spatial drawing and industrial-design sketching.", method: "Annex", methodText: "This selection accompanies the main portfolio by making visible the looking, precision and construction skills that support my design practice.", observation: "01 / Observation & colour", observationTitle: "Object studies", observationText: "Two coloured-pencil studies and a cut fruit: surface, light, material and structure are approached through the same attention to detail.", space: "02 / Spatial observation", spaceTitle: "Building sketch", spaceText: "An urban sketch built through line, depth and the rhythm of façades — a study of space as situated experience.", product: "03 / Analysis & project", productTitle: "Product analysis", productText: "From the disassembled object to use scenarios, this plate shows the passage from observation to formal and functional analysis.", industrial: "04 / Industrial-design sketches", industrialTitle: "Forms, systems, imaginaries", industrialText: "A series of coloured studies around objects, systems and their uses: PET FED, FLYER, RICE COOKER and DIGITAL.", plate: "Plate", close: "End of annex", next: "Back to projects"
  }
};

function Plate({ src, index, label, dark = false }: { src: string; index: number; label: string; dark?: boolean }) {
  return <figure className={`annex-plate ${dark ? "annex-plate--dark" : ""}`}><img src={src} alt={`${label} — plate ${index}`} /><figcaption><b>PLATE {String(index).padStart(2, "0")}</b><span>{label}</span></figcaption></figure>;
}

export default function Annex() { const { language } = useLanguage(); const t = copy[language]; return <main className="annex-page"><aside className="drawing-spine" aria-hidden="true"><span>ANNEX / 04</span><em>MIN GAO</em><b>2026</b></aside><section className="annex-hero"><Link href="/projects" className="back-link"><ArrowLeft size={15} />{t.back}</Link><div className="annex-hero-grid"><div><p className="kicker"><i />{t.kicker}</p><h1>{t.title}</h1><p className="drawing-lead">{t.intro}</p></div><div className="drawing-hero-note"><span>FILE / ANNEX—01</span><p>{t.description}</p><small>AUTHOR / MIN GAO · STATUS / APPLICATION MATERIAL</small></div></div></section><section className="annex-method"><div className="drawing-method-label"><span>00</span><h2>{t.method}</h2></div><p>{t.methodText}</p><div className="drawing-rule" /></section><section className="annex-section annex-section--observation"><header className="drawing-section-head"><div><p className="kicker"><i />{t.observation}</p><h2>{t.observationTitle}</h2></div><span>PLATES 01—03</span></header><p className="drawing-section-text">{t.observationText}</p><div className="annex-grid annex-grid--observation"><Plate src={plates[0]} index={1} label="REPRODUCTION / OBJECT" /><Plate src={plates[1]} index={2} label="COLOUR PENCIL / FORM" /><Plate src={plates[2]} index={3} label="COLOUR PENCIL / STRUCTURE" /></div></section><section className="annex-section annex-section--space"><header className="drawing-section-head"><div><p className="kicker"><i />{t.space}</p><h2>{t.spaceTitle}</h2></div><span>PLATE 04</span></header><p className="drawing-section-text">{t.spaceText}</p><div className="annex-single"><Plate src={plates[3]} index={4} label="LINE / DEPTH / RHYTHM" /></div></section><section className="annex-section annex-section--product"><header className="drawing-section-head"><div><p className="kicker"><i />{t.product}</p><h2>{t.productTitle}</h2></div><span>PLATE 05</span></header><p className="drawing-section-text">{t.productText}</p><div className="annex-single annex-single--wide"><Plate src={plates[4]} index={5} label="OBSERVATION / SYSTEM / USE" dark /></div></section><section className="annex-section annex-section--industrial"><header className="drawing-section-head"><div><p className="kicker"><i />{t.industrial}</p><h2>{t.industrialTitle}</h2></div><span>PLATES 06—07</span></header><p className="drawing-section-text">{t.industrialText}</p><div className="annex-grid annex-grid--industrial"><Plate src={plates[5]} index={6} label="COLOUR / PRODUCT FAMILY" /><Plate src={plates[6]} index={7} label="SYSTEM / IMAGINARY" /></div></section><section className="drawing-close"><div><span>{t.close}</span><strong>ANNEX / 04</strong></div><Link href="/projects">{t.next}<ArrowUpRight size={20} /></Link></section></main>; }
