import { ArrowUpRight, ArrowLeft } from "lucide-react";
import { Link } from "wouter";
import { useLanguage } from "@/contexts/LanguageContext";

const asset = (file: string) => `${import.meta.env.BASE_URL}assets/drawing/${file}`;
const plates = [1, 2, 3, 4, 5].map((n) => asset(`plate-${n}.jpg`));

const copy = {
  fr: { back: "Retour à l’archive", kicker: "04 / DESSIN", title: "Dessin", intro: "Observer, démonter, comprendre.", description: "Une archive de recherches graphiques et de dessin d’analyse, où la main devient un outil d’observation, de structure et de décision.", method: "Méthode", methodText: "Du contour à la coupe, du geste à la nomenclature : ces planches montrent comment le dessin transforme un objet quotidien en système lisible.", primary: "01 / Étude de produit", primaryTitle: "Commode — Logitech G Pro Wireless 1ère", primaryText: "Une séquence en trois temps : observation des silhouettes, décomposition des composants, puis synthèse des usages et des relations entre les pièces.", secondary: "02 / Étude de produit", secondaryTitle: "Incommode — Philips sèche-cheveux BHC016", secondaryText: "Une recherche plus rapide et plus matérielle, de la vue colorée aux géométries internes et aux familles de formes.", plate: "Planche", index: "Archive dessin", close: "Fin du dossier", next: "Voir les projets" },
  en: { back: "Back to archive", kicker: "04 / DRAWING", title: "Drawing", intro: "Observe, dismantle, understand.", description: "An archive of graphic research and analytical drawing, where the hand becomes a tool for observation, structure and decision-making.", method: "Method", methodText: "From contour to section, from gesture to nomenclature: these plates show how drawing turns an everyday object into a readable system.", primary: "01 / Product study", primaryTitle: "Commode — Logitech G Pro Wireless 1st generation", primaryText: "A three-part sequence: observing silhouettes, decomposing components, then synthesising use and the relations between parts.", secondary: "02 / Product study", secondaryTitle: "Incommode — Philips BHC016 hair dryer", secondaryText: "A quicker, more material study, moving from a colour rendering to internal geometries and families of forms.", plate: "Plate", index: "Drawing archive", close: "End of dossier", next: "View projects" }
};

export default function Drawing() { const { language } = useLanguage(); const t = copy[language]; return <main className="drawing-page"><aside className="drawing-spine" aria-hidden="true"><span>DRAWING / 04</span><em>MIN GAO</em><b>2026</b></aside><section className="drawing-hero"><Link href="/projects" className="back-link"><ArrowLeft size={15} />{t.back}</Link><div className="drawing-hero-grid"><div><p className="kicker"><i />{t.kicker}</p><h1>{t.title}</h1><p className="drawing-lead">{t.intro}</p></div><div className="drawing-hero-note"><span>FILE / 04—DRAWING</span><p>{t.description}</p><small>AUTHOR / MIN GAO · STATUS / SELECTED</small></div></div></section><section className="drawing-method"><div className="drawing-method-label"><span>00</span><h2>{t.method}</h2></div><p>{t.methodText}</p><div className="drawing-rule" /></section><section className="drawing-dossier drawing-dossier--primary"><header className="drawing-section-head"><div><p className="kicker"><i />{t.primary}</p><h2>{t.primaryTitle}</h2></div><span>PLATES 01—03</span></header><p className="drawing-section-text">{t.primaryText}</p><div className="drawing-plates drawing-plates--primary">{plates.slice(0,3).map((src, i) => <figure key={src} className={`drawing-plate drawing-plate--${i+1}`}><img src={src} alt={`${t.primaryTitle} — ${t.plate} ${i+1}`} /><figcaption><b>{t.plate} {String(i+1).padStart(2,"0")}</b><span>{i === 0 ? "OBSERVATION" : i === 1 ? "DECOMPOSITION" : "SYNTHESIS"}</span></figcaption></figure>)}</div></section><section className="drawing-dossier drawing-dossier--secondary"><header className="drawing-section-head"><div><p className="kicker"><i />{t.secondary}</p><h2>{t.secondaryTitle}</h2></div><span>PLATES 04—05</span></header><p className="drawing-section-text">{t.secondaryText}</p><div className="drawing-plates drawing-plates--secondary">{plates.slice(3).map((src, i) => <figure key={src} className="drawing-plate"><img src={src} alt={`${t.secondaryTitle} — ${t.plate} ${i+4}`} /><figcaption><b>{t.plate} {String(i+4).padStart(2,"0")}</b><span>{i === 0 ? "FORM STUDY" : "STRUCTURAL READING"}</span></figcaption></figure>)}</div></section><section className="drawing-close"><div><span>{t.close}</span><strong>{t.index}</strong></div><Link href="/projects">{t.next}<ArrowUpRight size={20} /></Link></section></main>; }
