/** 展览档案室设计提醒：案例页像独立展厅档案，先给题名与事实索引，再展开项目叙事和原始过程页。 */
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { Link, useRoute } from "wouter";
import { originalPages, projects } from "@/data/portfolio";
import { useLanguage } from "@/contexts/LanguageContext";

const copy = { fr:{ back:"Retour à l’index", context:"Contexte", approach:"Démarche", outcome:"Proposition", original:"Pages originales", next:"Projet suivant", role:"Rôle", place:"Lieu", year:"Année" }, en:{ back:"Back to index", context:"Context", approach:"Approach", outcome:"Proposal", original:"Original pages", next:"Next project", role:"Role", place:"Place", year:"Year" } };

export default function ProjectDetail() { const [, params] = useRoute("/projects/:slug"); const { language } = useLanguage(); const t = copy[language]; const project = projects.find((item) => item.slug === params?.slug); if (!project) return <main className="not-found"><h1>404</h1><Link href="/projects">{t.back}</Link></main>; const local = project[language]; const current = projects.findIndex((item) => item.slug === project.slug); const next = projects[(current + 1) % projects.length];
  return <main className="project-detail"><section className="detail-intro"><Link href="/projects" className="back-link"><ArrowLeft size={15} />{t.back}</Link><div className="detail-title"><div className="detail-code"><span>{project.id} / {project.category.toUpperCase()}</span><i className="mg-seal" aria-hidden="true" /></div><h1>{local.title}</h1><p>{local.subtitle}</p></div><div className="detail-facts"><div><span>{t.role}</span><strong>{local.role}</strong></div><div><span>{t.place}</span><strong>{local.location}</strong></div><div><span>{t.year}</span><strong>{local.year}</strong></div></div></section><figure className="detail-cover"><img src={project.image} alt={`${local.title} — original project page`} /><figcaption><i />{local.summary}</figcaption></figure><section className="case-study"><div className="case-rail"><span>MG / {project.id}</span><i /></div><div className="case-copy"><article><span>01</span><h2>{t.context}</h2><p>{local.context}</p></article><article><span>02</span><h2>{t.approach}</h2><p>{local.approach}</p></article><article><span>03</span><h2>{t.outcome}</h2><p>{local.outcome}</p></article></div></section><section className="original-pages"><div className="section-title-row"><div><p className="kicker"><i />{t.original}</p><h2>{local.title}</h2></div><span>{project.pages.map((page) => String(page).padStart(2,"0")).join(" · ")}</span></div><div className={`page-evidence page-evidence--${project.pages.length}`}>{project.pages.map((page, index) => <figure className="evidence-plate" key={page}><img src={originalPages[page - 1]} alt={`${local.title}, original portfolio page ${page}`} /><figcaption><span>PLATE {String(index + 1).padStart(2,"0")}</span><span>PAGE {String(page).padStart(2,"0")} / 27</span></figcaption></figure>)}</div></section><section className="next-project"><span>{t.next}</span><Link href={`/projects/${next.slug}`}><strong>{next[language].title}</strong><ArrowUpRight size={24} /></Link></section></main>;
}
