/** 展览档案室设计提醒：研究详情页像专业阅览室；元数据在上，原始研究页在同页连续呈现，不提供下载式操作。 */
import { ArrowLeft, ChevronDown } from "lucide-react";
import { Link, useRoute } from "wouter";
import { useLanguage } from "@/contexts/LanguageContext";
import { researchArticles } from "@/data/research";
import NotFound from "@/pages/NotFound";

const copy = { fr:{ back:"Retour aux recherches", question:"Question de recherche", keywords:"Mots-clés", author:"Auteur", interview:"Entretien", pages:"Étendue", reader:"Document original", readerNote:"Lecture intégrée · la consultation se poursuit directement dans cette page", more:"Autres recherches" }, en:{ back:"Back to research", question:"Research question", keywords:"Keywords", author:"Author", interview:"Interview", pages:"Extent", reader:"Original document", readerNote:"Embedded reading · continue directly on this page", more:"Further research" } };

export default function ResearchDetail() {
  const [, params] = useRoute("/writing/:slug"); const { language } = useLanguage(); const t = copy[language]; const article = researchArticles.find((entry) => entry.slug === params?.slug); if (!article) return <NotFound />; const item = article[language]; const next = researchArticles[(researchArticles.findIndex((entry) => entry.slug === article.slug) + 1) % researchArticles.length];
  return <main className="page-main reader-page"><aside className="reader-spine" aria-hidden="true"><i /><span>DOSSIER {article.id}</span><em>MIN GAO</em><b>2024—2026</b></aside><section className="reader-intro"><Link href="/writing" className="reader-back"><ArrowLeft size={15} />{t.back}</Link><div className="reader-title"><div className="reader-index"><span>{article.id}</span><small>MG / RESEARCH</small></div><div><p className="kicker"><i />{item.format}</p><div className="reader-classification"><span>FILE / {article.id}—04</span><span>STATUS / OPEN</span><span>AUTHOR / MIN GAO</span></div><h1>{item.title}</h1><p className="reader-summary">{item.summary}</p></div></div><aside className="reader-facts"><div><span>{t.author}</span><strong>Min Gao</strong></div>{item.interview && <div><span>{t.interview}</span><strong>{item.interview}</strong></div>}<div><span>{t.pages}</span><strong>{article.pages}</strong></div></aside></section><section className="reader-research"><div><span>{t.question}</span><p>{item.question}</p></div><div className="reader-keywords"><span>{t.keywords}</span><p>{item.keywords.map((keyword) => <em key={keyword}>{keyword}</em>)}</p></div></section><section className="document-reader" aria-label={t.reader}><div className="document-reader-head"><div><span>PLATE / {article.id}—04</span><h2>{t.reader}</h2></div><p>{t.readerNote}</p></div><div className="document-plate-meta"><span>ORIGINAL RESEARCH FILE</span><span>{item.format}</span><span>{article.pages}</span><span>MIN GAO / 2026</span></div><div className="document-frame"><span className="document-margin-note">ARCHIVE COPY / {article.id}</span><span className="document-page-note">ORIGINAL PAGINATION</span><div className="document-pages">{article.pageImages.map((image, index) => <figure key={image}><img src={image} alt={`${item.title} — page ${index + 1}`} loading={index > 1 ? "lazy" : "eager"} /><figcaption>PLATE {String(index + 1).padStart(2, "0")} / {article.pages}</figcaption></figure>)}</div></div></section><section className="reader-next"><div><span>{t.more}</span><small>INDEX / {next.id}—04 · STATUS / OPEN</small></div><Link href={`/writing/${next.slug}`}><strong>{next[language].title}</strong><ChevronDown size={18} /></Link></section></main>;
}
