/** 展览档案室设计提醒：写作页以“研究阅览桌”呈现，重点 dossier 是唯一大幅档案；暖白纸面、朱红索引和非对称栏位服务于可追溯的研究阅读。 */
import { ArrowUpRight, Download, FileText, Quote } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { researchArticles } from "@/data/research";

const copy = {
  fr: { kicker:"Écrits & recherches", title:"Écrire pour\nregarder autrement.", lead:"Notes critiques, enquêtes et études de cas. Chaque texte est pensé comme un dossier de recherche : une question, des traces, une position.", index:"04 / 04 dossiers classés", featured:"Dossier mis en avant", question:"Question de recherche", keywords:"Mots-clés", open:"Ouvrir le PDF", archive:"Consulter le dossier", collection:"Autres recherches", collectionLead:"Une sélection de notes qui relient dispositifs, cultures matérielles, espace et pouvoir.", by:"Par", interview:"Entretien", format:"Format", pages:"Étendue", document:"Document", status:"Statut", openStatus:"Ouvert" },
  en: { kicker:"Writing & research", title:"Writing to\nsee otherwise.", lead:"Critical notes, inquiries and case studies. Each text is conceived as a research dossier: a question, traces and a position.", index:"04 / 04 classified dossiers", featured:"Featured dossier", question:"Research question", keywords:"Keywords", open:"Open PDF", archive:"View dossier", collection:"Further research", collectionLead:"A selection of notes connecting apparatuses, material cultures, space and power.", by:"By", interview:"Interview", format:"Format", pages:"Extent", document:"Document", status:"Status", openStatus:"Open" }
};

export default function Writing() {
  const { language } = useLanguage();
  const t = copy[language];
  const featured = researchArticles.find((article) => article.featured)!;
  const featuredCopy = featured[language];
  const articles = researchArticles.filter((article) => !article.featured);
  return <main className="page-main writing-page">
    <aside className="writing-spine" aria-hidden="true"><i /><span>RESEARCH FILES</span><em>MIN GAO</em><b>2024—2026</b></aside>
    <section className="page-hero writing-hero writing-hero--archive"><p className="kicker"><i />02 / {t.kicker}</p><div className="page-hero-layout"><h1>{t.title.split("\n").map((line, index) => <span key={line} className={index === 1 ? "writing-title-accent" : undefined}>{line}</span>)}</h1><div className="writing-hero-note"><p>{t.lead}</p><div className="writing-ledger"><span>{t.document} / 02</span><span>AUTHOR / MIN GAO</span><span>{t.status} / {t.openStatus}</span></div><span>{t.index}</span></div></div></section>
    <section className="featured-dossier" aria-labelledby="featured-dossier-title"><div className="dossier-index" aria-hidden="true"><span>01</span><i /><small>MG / RESEARCH</small></div><div className="dossier-main"><div className="dossier-eyebrow"><span>{t.featured}</span><span>{featuredCopy.format}</span></div><h2 id="featured-dossier-title">{featuredCopy.title}</h2><p className="dossier-summary">{featuredCopy.summary}</p><div className="dossier-question"><Quote size={16} /><div><span>{t.question}</span><p>{featuredCopy.question}</p></div></div></div><aside className="dossier-facts"><dl><div><dt>{t.by}</dt><dd>{featuredCopy.credit.replace("Texte & enquête : ", "").replace("Text & research: ", "")}</dd></div><div><dt>{t.interview}</dt><dd>{featuredCopy.interview}</dd></div><div><dt>{t.format}</dt><dd>{featuredCopy.format}</dd></div><div><dt>{t.pages}</dt><dd>{featured.pages}</dd></div></dl><div className="dossier-keywords"><span>{t.keywords}</span><div>{featuredCopy.keywords.map((keyword) => <em key={keyword}>{keyword}</em>)}</div></div><a className="dossier-open" href={featured.pdf} target="_blank" rel="noreferrer"><FileText size={16} /><span>{t.archive}</span><ArrowUpRight size={16} /></a></aside></section>
    <section className="research-collection" aria-labelledby="research-collection-title"><div className="research-collection-head"><div><p className="kicker"><i />03 / {t.collection}</p><h2 id="research-collection-title">{t.collection}</h2></div><p>{t.collectionLead}</p></div><div className="research-grid">{articles.map((article) => { const item = article[language]; return <article className={`research-card research-card--${article.id}`} key={article.slug}><div className="research-card-top"><span>{article.id} / 04</span><span>{item.format}</span><span>{article.pages}</span></div><h3>{item.title}</h3><p>{item.summary}</p><div className="research-question"><span>{t.question}</span><strong>{item.question}</strong></div><p className="research-credit">{item.credit}</p><div className="research-card-bottom"><div className="research-keywords">{item.keywords.map((keyword) => <em key={keyword}>{keyword}</em>)}</div><a href={article.pdf} target="_blank" rel="noreferrer" aria-label={`${t.open}: ${item.title}`}><Download size={15} /><span>{t.open}</span></a></div></article>; })}</div></section>
  </main>;
}
